# Generated by Django 2.2 on 2019-04-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('relationship', models.CharField(default=1, max_length=100)),
                ('number', models.CharField(default='(123)-123-0000', max_length=100)),
            ],
        ),
    ]
