# Generated by Django 2.2 on 2019-04-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='1231230000', max_length=100)),
                ('carrier', models.CharField(choices=[('att', 'att'), ('tmobile', 'tmobile'), ('verizon', 'verizon'), ('sprint', 'sprint')], default='att', max_length=100)),
                ('cheap', models.IntegerField(default=2)),
                ('expensive', models.IntegerField(default=3)),
                ('popular', models.IntegerField(default=3)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='carrier',
            field=models.CharField(choices=[('att', 'att'), ('tmobile', 'tmobile'), ('verizon', 'verizon'), ('sprint', 'sprint')], default='att', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(default='1231230000', max_length=100),
        ),
    ]
